### ISSUE TITLE
改为监听0.0.0.0后，一直在试图连接IPV6的地址。

### ISSUE THREAD

**Issue by cklx0719** [journey-ad/Bitmagnet-Next-Web#1]
如题，连接IPV6地址连接不上。

![image](https://github.com/journey-ad/Bitmagnet-Next-Web/assets/25605487/ae3ae74a-ed27-4656-84bf-b39a5b8c3772)

**Comment by cklx0719** [comment]
在docker-compose.yml里，bitmagnet-next-web里加入
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=1"
 禁用掉IPV6，就可以正常连接了。

**Comment by journey-ad** [comment]
试一下`journey0ad/bitmagnet-next-web:test-1`这个镜像，监听地址改成了ipv6的`::`

**Comment by journey-ad** [comment]
已在 https://github.com/journey-ad/Bitmagnet-Next-Web/commit/2e634df92db36c0210919d348eb58771c4fc73bf 中修复
