### ISSUE TITLE
部署完成，但是搜不到东西

### ISSUE THREAD

**Issue by Vanhelsin21** [journey-ad/Bitmagnet-Next-Web#11]
已经用docker-compose 部署好了，但是搜索发现什么也搜不到，
目前看后端好像没有问题，但是前端似乎不起作用，不知道问题在哪里，不知道该怎么配置。
容器日志部分如下
<img width="468" alt="无标题" src="https://github.com/user-attachments/assets/20218d2d-8ca3-4606-8475-b94d59a13d14">
![image](https://github.com/user-attachments/assets/22884efe-31de-4a95-9128-920a69380f13)
![image](https://github.com/user-attachments/assets/41f7ad19-fc20-459b-804a-fdc25bafa138)

**Comment by journey-ad** [comment]
是不是数量太少了，用已有的关键词搜索看看，比如搜 **mp4**

**Comment by Vanhelsin21** [comment]
感谢大佬回复，应该是爬虫搜到资源还不够多的原因，此外，bitmagnet需要给挂一个梯子吗，我看日志里总是提示有github访问有问题的内容，此外通过tmdb削挂视频信息的时候似乎也会提示访问超时。

**Comment by journey-ad** [comment]
tmdb这个报错我没管它，不影响种子信息获取，之前关掉刮削好像是遇到了别的问题，所以没管。自己研究看看吧，也可以去bitmagnet的issues看看有没有相关讨论

**Comment by Vanhelsin21** [comment]
最后问个问题，说明里的这部分没看懂，想知道在哪里执行这个。。。
![image](https://github.com/user-attachments/assets/79568c0f-207a-4282-ac96-486cc044c449)

**Comment by journey-ad** [comment]
用sql客户端连到数据库，然后依次执行这几条语句，执行根据数据量可能会比较慢，要确保不会中断
