### ISSUE TITLE
请问运行中的程序如何建立索引呢？

### ISSUE THREAD

**Issue by 5536086** [journey-ad/Bitmagnet-Next-Web#3]
程序已经运行和几个月了，目前磁力很多了，搜索起来很慢，如何建立索引以提升搜索速度呢？

**Comment by 5536086** [comment]
创建索引报错
`postgres=# create extension pg_trgm;
CREATE EXTENSION
postgres=# CREATE INDEX idx_torrents_name_1 ON torrents USING gin (name gin_trgm_ops);
ERROR:  relation "torrents" does not exist
postgres=# CREATE INDEX idx_torrent_files_path_1 ON torrent_files USING gin (path gin_trgm_ops);
ERROR:  relation "torrent_files" does not exist
`

**Comment by journey-ad** [comment]
先执行 `\c bitmagnet` 切换到 **bitmagnet** 数据库，之后再执行创建索引的命令

另外运行几个月的数据可能有上千万条，添加索引可能要几个小时，需要保证执行环境不会意外关闭，或者用CONCURRENTLY模式在后台运行索引

**Comment by 5536086** [comment]
> 先执行 `\c bitmagnet` 切换到 **bitmagnet** 数据库，之后再执行创建索引的命令
> 
> 另外运行几个月的数据可能有上千万条，添加索引可能要几个小时，需要保证执行环境不会意外关闭，或者用CONCURRENTLY模式在后台运行索引

确实数据很多，在screen后台执行的，都执行完了，但是感觉改善并不太明显呢，还有没有别的改善方法呢？

**Comment by journey-ad** [comment]
软件层面目前就是这样了，不过可以从硬件层面考虑，用更强的cpu、数据库放在ssd之类

我对后端开发和数据库不太熟悉，目前的方案已经是我的能力极限了，之后对数据库优化有更深入的了解也会用到这个项目里，如果有熟悉数据库查询优化的欢迎pr😀

**Comment by 5536086** [comment]
> 软件层面目前就是这样了，不过可以从硬件层面考虑，用更强的cpu、数据库放在ssd之类
> 
> 我对后端开发和数据库不太熟悉，目前的方案已经是我的能力极限了，之后对数据库优化有更深入的了解也会用到这个项目里，如果有熟悉数据库查询优化的欢迎pr😀

好的，谢谢

**Comment by journey-ad** [comment]
@5536086 关于搜索性能问题，可以尝试部署下 Meilisearch，目前还在 dev 分支，可以参考下文档 [(可选)使用 Meilisearch 增强搜索性能](https://github.com/journey-ad/Bitmagnet-Next-Web/blob/dev/README_zh-CN.md#%E5%8F%AF%E9%80%89%E4%BD%BF%E7%94%A8-meilisearch-%E5%A2%9E%E5%BC%BA%E6%90%9C%E7%B4%A2%E6%80%A7%E8%83%BD) 这部分

实测效果速度提升很不错，不过坑也蛮多的，适合作为高阶用法，meilisync 这个工具不是很完善，可能要多翻翻它的 issue
