### ISSUE TITLE
Bitmagnet-Next-Web无法使用

### ISSUE THREAD

**Issue by cuijianzhuang** [journey-ad/Bitmagnet-Next-Web#4]
docker部署的，这个页面有问题
![image](https://github.com/user-attachments/assets/bb04eef7-c8a3-4955-93c7-0fac35020f5c)
![image](https://github.com/user-attachments/assets/710793a7-6990-4119-b808-f75d50d93584)

**Comment by journey-ad** [comment]
参考 #1 ，`test-1`镜像可用的话麻烦告知下

**Comment by cuijianzhuang** [comment]
test-1镜像可用，可以了

**Comment by journey-ad** [comment]
已同步更新到`latest` https://github.com/journey-ad/Bitmagnet-Next-Web/commit/2e634df92db36c0210919d348eb58771c4fc73bf
