### ISSUE TITLE
有没有一键部署的docker命令啊

### ISSUE THREAD

**Issue by xiankaiyao** [journey-ad/Bitmagnet-Next-Web#5]
小白看这个太复杂了，搞不定

**Comment by journey-ad** [comment]
Docker Compose 已经算得上是一键部署了，建议先找一些文章或视频教程，了解你所用环境里 Docker Compose 的用法
对于不支持 Compose 的环境，README 里也提供了手动运行容器的命令，可以根据实际情况调整参数来运行容器

Docker 是非常简化的部署方式，最大的问题在于你的环境对 Docker 的支持情况和使用方式。这部分问题和本项目没有关系，建议自己查资料解决
