### ISSUE TITLE
希望支持vercel部署

### ISSUE THREAD

**Issue by xfxx2022** [journey-ad/Bitmagnet-Next-Web#6]
等待更新vercel部署教程

**Comment by journey-ad** [comment]
我不确定原始的 bitmagnet 能否在 vercel 部署，另外运行几个月的数据将达到千万级别，数据库大小可能上百G，不确定 vercel 的数据库能否支持这种规模的数据

如果只是需要部署前端，传入以下环境变量就可以：
- `POSTGRES_DB_URL` 数据库连接串
- `NEXT_PUBLIC_BASE_URL` 站点地址
