### ISSUE TITLE
locales 添加了这个变量zh-CN也没有切换到中文

### ISSUE THREAD

**Issue by zhangxuan1340** [journey-ad/Bitmagnet-Next-Web#8]
具体是哪个参数管控切换语言,我看了一下in18有语言文件

**Comment by journey-ad** [comment]
默认读浏览器语言，也可以在首页右上角切换

**Comment by zhangxuan1340** [comment]
![20240912161230](https://github.com/user-attachments/assets/931c18bb-ecd8-4d4a-9ecb-508ca21c3c50)
那能看看我这个为啥没有语言切换按钮

**Comment by journey-ad** [comment]
你发的是bitmagnet原版的webui

本程序运行在3000端口上，界面如下：
![](https://github.com/journey-ad/Bitmagnet-Next-Web/raw/main/.readme/zh_Index.jpg)

**Comment by zhangxuan1340** [comment]
这样阿，我再拉取一下本项目试试看
